name: build
on:
  release:
    types: [created]
  push:
    branches:
      - '**'
env:
  # renovate: datasource=npm depName=npm
  NPM_VERSION: '11'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: npm
      - run: npm install -g npm@${{ env.NPM_VERSION }} --registry=https://registry.npmjs.org
      - run: npm ci
      - uses: microbit-foundation/npm-package-versioner-action@v3
      - run: npm run build
      - run: npm pack
      - uses: actions/upload-artifact@v7
        if: github.event_name == 'release'
        with:
          name: npm-tarball
          path: '*.tgz'
          if-no-files-found: error
          retention-days: 1

  publish:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    environment: npm-publish
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: npm-tarball
      - uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm@${{ env.NPM_VERSION }} --registry=https://registry.npmjs.org
      - run: npm stage publish --allow-file=all ./*.tgz
